# These are supported funding model platforms

github: elleshadow  # Replace with your GitHub username
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
liberapay: # Replace with a single Liberapay username
custom: # Replace with up to 4 custom sponsorship URLs