repository:
  # Repository name
  name: dev-ops-tui
  
  # Repository description
  description: A powerful Terminal User Interface (TUI) library for DevOps tools, built in pure Bash
  
  # Homepage URL (optional)
  homepage: https://github.com/yourusername/dev-ops-tui
  
  # Topics to categorize your repository
  topics:
    - bash
    - tui
    - terminal
    - devops
    - dialog
    - shell-script
    - automation
    - cli
    - terminal-ui
  
  # Repository features
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  
  # Branch protection
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

# Labels for issues and pull requests
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  
  - name: enhancement
    color: a2eeef
    description: New feature or request
  
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  
  - name: question
    color: d876e3
    description: Further information is requested
  
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file

# Branch protection rules
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ['test', 'lint']
      enforce_admins: false
      restrictions: null 