# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed
daysUntilClose: 7

# Issues or Pull Requests with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - bug
  - enhancement
  - documentation

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale
markComment: >
  This issue/PR has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when closing a stale Issue or Pull Request
closeComment: >
  This issue/PR has been automatically closed because it has not had
  recent activity. Please feel free to reopen it if needed.

# Limit to only `issues` or `pulls`
only: issues

# Set to true to ignore issues with an assignee
exemptAssignees: true

# Label to use when removing the stale label
unmarkLabel: active

# Comment to post when removing the stale label
unmarkComment: >
  This issue/PR is no longer marked as stale because there has been recent activity. 