extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  document-start:
    present: false
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  key-duplicates: enable
  new-line-at-end-of-file: enable
  trailing-spaces: enable
  octal-values: disable

ignore: |
  node_modules/
  vendor/ 