site_name: Dev-Ops TUI Documentation
site_url: https://elleshadow.github.io/dev-ops-tui
repo_name: elleshadow/dev-ops-tui
repo_url: https://github.com/elleshadow/dev-ops-tui
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true
  - git-committers:
      repository: elleshadow/dev-ops-tui
      branch: main
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - tags:
      tags_file: tags.md
  - awesome-pages
  - glightbox:
      auto_caption: true
  - redirects:
      redirect_maps:
        'old/path.md': 'new/path.md'
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - swagger-ui-tag
  - macros

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - abbr
  - tables
  - toc:
      permalink: true
      title: On this page
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Configuration: configuration.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Dialog Components: user-guide/dialog-components.md
    - Forms & Input: user-guide/forms-and-input.md
    - Menus & Selection: user-guide/menus-and-selection.md
    - File Operations: user-guide/file-operations.md
    - Progress Indicators: user-guide/progress-indicators.md
  - API Reference:
    - Core API: api/core.md
    - Dialog API: api/dialog.md
    - Form API: api/form.md
    - Menu API: api/menu.md
    - Utility API: api/utility.md
  - Development:
    - Contributing: contributing.md
    - Code Style: development/code-style.md
    - Testing: development/testing.md
    - Release Process: development/release-process.md
  - Blog:
    - blog/index.md
  - About:
    - Changelog: changelog.md
    - License: license.md
    - Authors: authors.md

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/elleshadow
  version:
    provider: mike
    default: latest
  tags:
    HTML5: html
    JavaScript: javascript
    CSS: css
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js