name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate Changelog
      id: changelog
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          git log --pretty=format:"* %s (%h)" > CHANGES.md
        else
          git log --pretty=format:"* %s (%h)" $PREVIOUS_TAG..HEAD > CHANGES.md
        fi
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat CHANGES.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release Archive
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        ARCHIVE="dev-ops-tui-${VERSION}.tar.gz"
        tar --exclude='.git' --exclude='.github' -czf "$ARCHIVE" .
        echo "archive=$ARCHIVE" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGES.md
        files: ${{ env.archive }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 